# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "elearning-sim-terraform-state"
    encrypt = true
    key     = "aws/prod/us-east-1/ecr/terraform.tfstate"
    region  = "us-east-1"
  }
}
